jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
    # Install docfx, stick with version 2.51 as higher versions result in https://github.com/dotnet/docfx/issues/5785 > fixed in 2.56.4+
    - name: Install dependencies
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.56.7/docfx.zip
        sudo unzip docfx.zip -d /usr/local/lib/docfx
        rm docfx.zip
        echo '#!/bin/sh' | sudo tee -a /usr/local/bin/docfx > /dev/null
        echo 'exec `which mono` $MONO_OPTIONS /usr/local/lib/docfx/docfx.exe "$@"' | sudo tee -a /usr/local/bin/docfx > /dev/null
        sudo chmod +wx /usr/local/bin/docfx
        sudo mkdir /usr/local/lib/docfx/plugins
        sudo cp ./main/docfx/plugins/* /usr/local/lib/docfx/plugins
    
    # Build docs
    - name: Build docs
      shell: pwsh
      run: |
        ./main/docfx/build.ps1